import { 
  Property, 
  LandListing, 
  Vehicle, 
  Dealership, 
  Experience, 
  Stay, 
  Agent, 
  Agency, 
  Area, 
  CRMLead, 
  BookingReservation, 
  Conversation, 
  ChatMessage, 
  AdCampaign, 
  Invoice, 
  Review, 
  BlogPost, 
  BrandSettings, 
  CustomFieldDefinition, 
  User,
  AppNotification,
  ActivityEvent
} from '../types';

export const INITIAL_BRAND_SETTINGS: BrandSettings = {
  brandName: 'SWAHIVO',
  tagline: 'Premier Marketplace for Properties, Land, Stays & Bookings',
  logoUrl: 'https://images.unsplash.com/photo-1541971875076-8f970d573be6?w=200&auto=format&fit=crop&q=80',
  darkLogoUrl: 'https://images.unsplash.com/photo-1541971875076-8f970d573be6?w=200&auto=format&fit=crop&q=80',
  faviconUrl: '/favicon.ico',
  primaryColor: '#e11d48', // Coral / Red Accent
  secondaryColor: '#f43f5e',
  accentColor: '#1e293b',
  supportEmail: 'contact@swahivo.com',
  supportPhone: '+1 (800) 555-0199',
  supportWhatsapp: '+1 (800) 555-0199',
  officeAddress: '100 Ocean Blvd, Suite 400',
  heroHeadline: 'Find Your Perfect Sanctuary',
  heroSubheadline: 'Discover verified luxury homes, investment land, commercial developments, quality vehicles, boutique stays and authentic experiences.',
  heroImageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1920&auto=format&fit=crop&q=85',
  defaultCurrency: 'USD',
  exchangeRates: {
    USD: 1,
    KES: 130,
    TZS: 2600,
    UGX: 3750,
    RWF: 1350,
    ETB: 120,
    EUR: 0.92,
    GBP: 0.78
  },
  socials: {
    facebook: 'https://facebook.com/swahivo',
    twitter: 'https://twitter.com/swahivo',
    instagram: 'https://instagram.com/swahivo',
    linkedin: 'https://linkedin.com/company/swahivo',
    youtube: 'https://youtube.com/c/swahivo',
    tiktok: 'https://tiktok.com/@swahivo'
  }
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_nayyar',
    name: 'Nayyar Shaikh',
    email: 'nayyar@safarinest.africa',
    phone: '+254 722 554 433',
    whatsapp: '+254 722 554 433',
    role: 'agent',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    status: 'active',
    membershipTier: 'agency',
    agencyId: 'agency_pamgolding',
    location: 'Westlands, Nairobi',
    createdAt: '2025-02-15',
    bio: 'Senior Luxury Real Estate Specialist covering Nairobi prime suburbs and Zanzibar coastal villas.'
  },
  {
    id: 'usr_superadmin',
    name: 'Arthur Taylor',
    email: 'arthur@safarinest.africa',
    phone: '+254 711 223 344',
    whatsapp: '+254 711 223 344',
    role: 'superadmin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    status: 'active',
    membershipTier: 'enterprise',
    location: 'Nairobi, Kenya',
    createdAt: '2025-01-10',
    bio: 'Founder & Platform Administrator of SafariNest East Africa.'
  },
  {
    id: 'usr_dealer_hassan',
    name: 'Hassan Mwinyi',
    email: 'hassan@mwinyiauto.co.tz',
    phone: '+255 777 443 210',
    whatsapp: '+255 777 443 210',
    role: 'vehicle_dealer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    status: 'active',
    membershipTier: 'pro',
    dealershipId: 'dealer_kilimanjaro',
    location: 'Dar es Salaam, Tanzania',
    createdAt: '2025-03-01',
    bio: 'Executive Director of Kilimanjaro Motors & East African Overland Imports.'
  },
  {
    id: 'usr_marcus',
    name: 'Marcus Vance',
    email: 'marcus.vance@investcapital.co.uk',
    phone: '+44 7700 900123',
    whatsapp: '+44 7700 900123',
    role: 'buyer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    status: 'active',
    membershipTier: 'pro',
    location: 'London & Nairobi',
    createdAt: '2025-04-12',
    bio: 'UK Diaspora Angel Investor acquiring high-yield commercial & gated luxury villas in Kenya.'
  },
  {
    id: 'usr_amina',
    name: 'Amina Kimaro',
    email: 'amina.kimaro@zanzibarrealty.co.tz',
    phone: '+255 778 998 877',
    whatsapp: '+255 778 998 877',
    role: 'agent',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    status: 'active',
    membershipTier: 'agency',
    agencyId: 'agency_zanzibar_realty',
    location: 'Stone Town, Zanzibar',
    createdAt: '2025-02-20',
    bio: 'Zanzibar Legal & Coastal Property Consultant specializing in ZIPA foreign-owned beachfront land.'
  },
  {
    id: 'usr_sarah',
    name: 'Sarah Jenkins',
    email: 'sarah.j@gmail.com',
    phone: '+1 415 889 2200',
    whatsapp: '+1 415 889 2200',
    role: 'visitor',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    status: 'active',
    membershipTier: 'free',
    location: 'San Francisco, USA',
    createdAt: '2025-06-05',
    bio: 'Safari & boutique eco-lodge explorer planning multi-country East Africa holiday.'
  }
];

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'agent_nayyar',
    name: 'Nayyar Shaikh',
    slug: 'nayyar-shaikh',
    title: 'Principal Luxury Property Advisor',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
    agencyId: 'agency_pamgolding',
    agencyName: 'Pam Golding Properties East Africa',
    phone: '+254 722 554 433',
    whatsapp: '+254 722 554 433',
    email: 'nayyar.shaikh@safarinest.africa',
    licenseNumber: 'EARB/2022/8892',
    areasServed: ['Westlands', 'Karen', 'Gigiri', 'Muthaiga', 'Zanzibar'],
    languages: ['English', 'Swahili', 'Hindi'],
    bio: 'Over 12 years of experience matching high-net-worth buyers with prime residences, golf estate villas, and commercial developments across Kenya and Tanzania.',
    rating: 4.96,
    reviewsCount: 38,
    activeListingsCount: 14,
    dealsClosed: 62,
    experienceYears: 12,
    isVerified: true,
    socials: { linkedin: '#', twitter: '#' }
  },
  {
    id: 'agent_amina',
    name: 'Amina Kimaro',
    slug: 'amina-kimaro',
    title: 'Coastal & Island Property Consultant',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    agencyId: 'agency_zanzibar_realty',
    agencyName: 'Zanzibar Coral Coast Properties',
    phone: '+255 776 890 123',
    whatsapp: '+255 776 890 123',
    email: 'amina@zanzibarrealty.co.tz',
    licenseNumber: 'TZ-RE-4410',
    areasServed: ['Nungwi', 'Paje', 'Kendwa', 'Stone Town', 'Dar es Salaam'],
    languages: ['Swahili', 'English', 'French', 'Italian'],
    bio: 'Specialist in beachfront villas, hotel development plots, and luxury short-term rental acquisitions across Zanzibar and the Tanzanian coast.',
    rating: 5.0,
    reviewsCount: 47,
    activeListingsCount: 9,
    dealsClosed: 41,
    experienceYears: 9,
    isVerified: true
  },
  {
    id: 'agent_david',
    name: 'David Mugisha',
    slug: 'david-mugisha',
    title: 'Kigali & Great Lakes Investment Specialist',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80',
    agencyId: 'agency_century_rwanda',
    agencyName: 'Century Real Estate Rwanda',
    phone: '+250 788 332 110',
    whatsapp: '+250 788 332 110',
    email: 'david@centuryrwanda.rw',
    licenseNumber: 'RDB-RE-9921',
    areasServed: ['Kiyovu', 'Nyarutarama', 'Gacuriro', 'Kimihurura'],
    languages: ['Kinyarwanda', 'English', 'French'],
    bio: 'Expert in Kigali diplomatic residences, eco-villas, and commercial properties in Rwanda’s high-growth capital.',
    rating: 4.88,
    reviewsCount: 29,
    activeListingsCount: 8,
    dealsClosed: 35,
    experienceYears: 8,
    isVerified: true
  },
  {
    id: 'agent_faith',
    name: 'Faith Chebet',
    slug: 'faith-chebet',
    title: 'Rift Valley & Agricultural Land Specialist',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80',
    agencyId: 'agency_rift_land',
    agencyName: 'Rift Valley Land & Ranch Advisory',
    phone: '+254 733 998 877',
    whatsapp: '+254 733 998 877',
    email: 'faith.chebet@safarinest.africa',
    licenseNumber: 'EARB/2021/7102',
    areasServed: ['Naivasha', 'Nanyuki', 'Nakuru', 'Laikipia', 'Eldoret'],
    languages: ['English', 'Swahili', 'Kalenjin'],
    bio: 'Guiding investors, diaspora buyers, and agribusiness corporations through secure titled land acquisitions across Kenya’s Rift Valley and Mount Kenya regions.',
    rating: 4.94,
    reviewsCount: 31,
    activeListingsCount: 16,
    dealsClosed: 54,
    experienceYears: 11,
    isVerified: true
  },
  {
    id: 'agent_brian',
    name: 'Brian Okello',
    slug: 'brian-okello',
    title: 'Uganda & Kampala Prime Broker',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    agencyId: 'agency_kampala_estates',
    agencyName: 'Kampala Premier Estates',
    phone: '+256 701 445 566',
    whatsapp: '+256 701 445 566',
    email: 'brian@kampalaestates.ug',
    licenseNumber: 'AREA/UG/2020/55',
    areasServed: ['Kololo', 'Nakasero', 'Bugolobi', 'Munonyo', 'Entebbe'],
    languages: ['English', 'Luganda', 'Swahili'],
    bio: 'Specializing in Lake Victoria waterfront properties, diplomatic rentals in Kololo, and modern luxury townhomes in Kampala.',
    rating: 4.91,
    reviewsCount: 24,
    activeListingsCount: 11,
    dealsClosed: 29,
    experienceYears: 7,
    isVerified: true
  }
];

export const INITIAL_AGENCIES: Agency[] = [
  {
    id: 'agency_pamgolding',
    name: 'Pam Golding Properties East Africa',
    slug: 'pam-golding-properties-east-africa',
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    tagline: 'International Real Estate Excellence in Kenya & Tanzania',
    description: 'The premier luxury residential and commercial property firm in East Africa with offices in Nairobi, Mombasa, and Dar es Salaam.',
    city: 'Nairobi',
    country: 'Kenya',
    address: 'Fortis Tower, 9th Floor, Woodvale Grove, Westlands',
    phone: '+254 700 889 900',
    whatsapp: '+254 700 889 900',
    email: 'info.kenya@pamgolding.co.ke',
    website: 'https://pamgolding.co.za',
    agentsCount: 28,
    listingsCount: 145,
    rating: 4.95,
    reviewsCount: 112,
    isVerified: true
  },
  {
    id: 'agency_zanzibar_realty',
    name: 'Zanzibar Coral Coast Properties',
    slug: 'zanzibar-coral-coast-properties',
    logo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=80',
    tagline: 'Your Gateway to Oceanfront Luxury in Zanzibar Archipelago',
    description: 'Specialists in ZIPA-compliant foreign investor villas, beachfront hotel plots, and luxury serviced stays in Unguja and Pemba.',
    city: 'Zanzibar',
    country: 'Tanzania',
    address: 'Shangani Street, Stone Town, Zanzibar',
    phone: '+255 777 999 888',
    whatsapp: '+255 777 999 888',
    email: 'hello@zanzibarrealty.co.tz',
    website: 'https://zanzibarrealty.co.tz',
    agentsCount: 12,
    listingsCount: 56,
    rating: 4.92,
    reviewsCount: 68,
    isVerified: true
  },
  {
    id: 'agency_century_rwanda',
    name: 'Century Real Estate Rwanda',
    slug: 'century-real-estate-rwanda',
    logo: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80',
    tagline: 'Leading Kigali Residential & Commercial Developments',
    description: 'Providing full-cycle real estate advisory, property management, and foreign buyer representation in Kigali.',
    city: 'Kigali',
    country: 'Rwanda',
    address: 'Grand Pension Plaza, Boulevard de la Révolution, Kigali',
    phone: '+250 788 123 456',
    whatsapp: '+250 788 123 456',
    email: 'contact@centuryrwanda.rw',
    website: 'https://centuryrwanda.rw',
    agentsCount: 16,
    listingsCount: 78,
    rating: 4.89,
    reviewsCount: 53,
    isVerified: true
  }
];

export const INITIAL_DEALERSHIPS: Dealership[] = [
  {
    id: 'dealer_kilimanjaro',
    name: 'Kilimanjaro Motors & Luxury Imports',
    slug: 'kilimanjaro-motors-luxury-imports',
    logo: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=80',
    tagline: 'Verified Japanese, UK & German Luxury Vehicle Importers',
    description: 'Premier East African dealership importing high-spec Land Cruisers, Range Rovers, Mercedes-Benz, and electric hybrids with full warranty and duty clearance.',
    country: 'Kenya',
    city: 'Nairobi',
    address: 'Mombasa Road Showroom, Near City Cabanas, Nairobi',
    phone: '+254 712 345 678',
    whatsapp: '+254 712 345 678',
    email: 'sales@kilimanjaromotors.co.ke',
    website: 'https://kilimanjaromotors.co.ke',
    establishedYear: 2014,
    inventoryCount: 42,
    isVerified: true,
    rating: 4.93,
    reviewsCount: 88,
    openingHours: 'Mon - Sat: 8:00 AM - 6:30 PM',
    specialties: ['Toyota Land Cruiser LC300 & Prado', 'Range Rover & Defender', 'Mercedes G-Class & GLE', 'Duty Paid Imports']
  },
  {
    id: 'dealer_tanzania_prime',
    name: 'Dar es Salaam Auto Gallery',
    slug: 'dar-es-salaam-auto-gallery',
    logo: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80',
    tagline: 'Tanzania’s Most Trusted Executive Vehicle Showroom',
    description: 'Showcasing inspected SUVs, commercial Hilux pickups, safari customized vehicles, and luxury executive sedans.',
    country: 'Tanzania',
    city: 'Dar es Salaam',
    address: 'Ali Hassan Mwinyi Road, Oysterbay, Dar es Salaam',
    phone: '+255 754 112 233',
    whatsapp: '+255 754 112 233',
    email: 'info@darautogallery.co.tz',
    website: 'https://darautogallery.co.tz',
    establishedYear: 2016,
    inventoryCount: 35,
    isVerified: true,
    rating: 4.88,
    reviewsCount: 64,
    openingHours: 'Mon - Sat: 8:30 AM - 6:00 PM',
    specialties: ['Custom Safari 4x4 Cruisers', 'Hilux & Isuzu D-Max', 'Lexus LX600', 'Trade-Ins Welcome']
  }
];

export const INITIAL_AREAS: Area[] = [
  {
    id: 'area_westlands',
    name: 'Westlands',
    slug: 'westlands',
    city: 'Nairobi',
    country: 'Kenya',
    description: 'The bustling commercial, diplomatic, and upscale residential hub of Nairobi filled with high-rise luxury towers and cosmopolitan restaurants.',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop&q=80',
    propertiesCount: 84,
    avgPriceSqft: 210,
    highlights: ['Expressway Access', 'Sarit & Westgate Malls', 'Diplomatic Missions', 'Vibrant Nightlife'],
    coordinates: { lat: -1.2683, lng: 36.8044 }
  },
  {
    id: 'area_karen',
    name: 'Karen',
    slug: 'karen',
    city: 'Nairobi',
    country: 'Kenya',
    description: 'Prestige leafy residential suburb known for lush acre plots, golf clubs, international schools, and colonial-heritage tranquil estates.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    propertiesCount: 62,
    avgPriceSqft: 280,
    highlights: ['Karen Country Club', 'Giraffe Centre', 'Spacious Acre Compounds', 'Top Tier Academies'],
    coordinates: { lat: -1.3197, lng: 36.7065 }
  },
  {
    id: 'area_nungwi',
    name: 'Nungwi Beach',
    slug: 'nungwi',
    city: 'Zanzibar',
    country: 'Tanzania',
    description: 'Famous turquoise water paradise on the northern tip of Zanzibar with non-tidal swimming, luxury beachfront villas and yachting.',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
    propertiesCount: 45,
    avgPriceSqft: 340,
    highlights: ['White Sand Beach', 'Sunset Dhow Cruises', 'ZIPA Foreign Ownership Allowed', 'High Rental Yields'],
    coordinates: { lat: -5.7258, lng: 39.2974 }
  },
  {
    id: 'area_kiyovu',
    name: 'Kiyovu',
    slug: 'kiyovu',
    city: 'Kigali',
    country: 'Rwanda',
    description: 'The Beverly Hills of Kigali: home to embassies, ministerial residences, panoramic green hill views and immaculate paved avenues.',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80',
    propertiesCount: 38,
    avgPriceSqft: 260,
    highlights: ['Diplomatic Enclave', '10 mins to CBD', 'Safe & Clean Streets', 'High Capital Appreciation'],
    coordinates: { lat: -1.9567, lng: 30.0619 }
  },
  {
    id: 'area_oysterbay',
    name: 'Oysterbay & Masaki',
    slug: 'oysterbay-masaki',
    city: 'Dar es Salaam',
    country: 'Tanzania',
    description: 'The exclusive coastal peninsula of Dar es Salaam featuring private marinas, gourmet seafood bistros and diplomatic compounds.',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&auto=format&fit=crop&q=80',
    propertiesCount: 51,
    avgPriceSqft: 240,
    highlights: ['Indian Ocean Frontage', 'Yacht Club', 'Coco Beach Promenade', 'International Hub'],
    coordinates: { lat: -6.7578, lng: 39.2789 }
  },
  {
    id: 'area_kololo',
    name: 'Kololo Hill',
    slug: 'kololo',
    city: 'Kampala',
    country: 'Uganda',
    description: 'Kampala’s most prestigious residential address crowning the city with serene boulevards, luxury penthouses and international embassies.',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80',
    propertiesCount: 34,
    avgPriceSqft: 220,
    highlights: ['Panoramic Hill Views', 'Golf Course Proximity', 'Expat Friendly', 'Gated Security'],
    coordinates: { lat: 0.3278, lng: 32.5932 }
  }
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop_karen_villa',
    title: 'The Orchid Grand Estate - 5 Bedroom Luxury Villa',
    slug: 'orchid-grand-estate-karen-nairobi',
    description: 'Set on 1.25 acres of manicured botanical gardens in the heart of Karen, this architectural masterpiece combines timeless contemporary aesthetics with authentic East African hardwood finishes. Features a heated infinity swimming pool, dedicated gym, smart home automation, high-ceiling reception salon, and a private guest cottage.',
    purpose: 'buy',
    propertyType: 'villa',
    price: 1450000,
    pricePeriod: 'total',
    currency: 'USD',
    country: 'Kenya',
    region: 'Nairobi County',
    city: 'Nairobi',
    area: 'Karen',
    address: 'Miotoni Road, Karen, Nairobi',
    coordinates: { lat: -1.3210, lng: 36.7110 },
    bedrooms: 5,
    bathrooms: 6,
    propertySizeSqft: 7200,
    landSizeSqft: 54450,
    landAcreage: 1.25,
    yearBuilt: 2024,
    parkingSpaces: 6,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=85',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTourUrl: 'https://my.matterport.com/show/?m=sample_tour',
    features: ['Heated Infinity Pool', 'Solar Power 15kVA', 'Borehole with Filtration', 'Smart Lighting', 'Staff Quarters for 3', 'Guard House', 'Wine Cellar', 'CCTV & Electric Fence'],
    amenities: ['Air Conditioning', 'High Speed Fibre', 'Gym', 'Balcony', 'Garden', 'Security 24/7', 'Fireplace'],
    floorPlans: [
      { id: 'fp1', title: 'Ground Floor Living & Terrace', bedrooms: 2, bathrooms: 2, sizeSqft: 4100, imageUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80' },
      { id: 'fp2', title: 'First Floor Master & Family Suite', bedrooms: 3, bathrooms: 4, sizeSqft: 3100, imageUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80' }
    ],
    status: 'published',
    isFeatured: true,
    isVerified: true,
    isOpenHouse: true,
    openHouseDate: '2026-09-12 10:00 AM - 4:00 PM',
    viewsCount: 3420,
    favoritesCount: 184,
    inquiriesCount: 29,
    rating: 4.98,
    reviewsCount: 14,
    agentId: 'agent_nayyar',
    agencyId: 'agency_pamgolding',
    createdAt: '2025-08-10',
    updatedAt: '2025-08-28'
  },
  {
    id: 'prop_zanzibar_ocean',
    title: 'The Coral Reef Horizon - Beachfront Pool Villa',
    slug: 'coral-reef-horizon-beachfront-villa-zanzibar',
    description: 'Direct ocean frontage on Zanzibar’s Nungwi beach. Designed for luxury holiday home living or high-return short-term vacation rental yield (14%+ ROI). Offers 4 private ensuite master suites with ocean balconies, private pool, dhow-wood bar, and full staff management.',
    purpose: 'buy',
    propertyType: 'villa',
    price: 920000,
    pricePeriod: 'total',
    currency: 'USD',
    country: 'Tanzania',
    region: 'Zanzibar North',
    city: 'Zanzibar',
    area: 'Nungwi Beach',
    address: 'Ras Nungwi Ocean Front, Zanzibar',
    coordinates: { lat: -5.7280, lng: 39.2990 },
    bedrooms: 4,
    bathrooms: 5,
    propertySizeSqft: 5100,
    landSizeSqft: 21780,
    landAcreage: 0.5,
    yearBuilt: 2023,
    parkingSpaces: 4,
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=85',
    virtualTourUrl: 'https://my.matterport.com/show/?m=sample_tour',
    features: ['Direct Beach Access', 'Infinity Pool overlooking Reef', 'ZIPA Foreign Title Ready', 'Fully Furnished with Coastal Teak', 'Desalination Plant', 'Generator Backup'],
    amenities: ['Sea View', 'Private Pool', 'Air Conditioning', 'WiFi', 'Chef Service Available'],
    status: 'published',
    isFeatured: true,
    isVerified: true,
    viewsCount: 4890,
    favoritesCount: 312,
    inquiriesCount: 45,
    rating: 5.0,
    reviewsCount: 22,
    agentId: 'agent_amina',
    agencyId: 'agency_zanzibar_realty',
    createdAt: '2025-08-14',
    updatedAt: '2025-08-30'
  },
  {
    id: 'prop_westlands_penthouse',
    title: 'Skyline Pinnacle Duplex Penthouse',
    slug: 'skyline-pinnacle-duplex-penthouse-westlands',
    description: 'Occupying the 28th and 29th floors with 360-degree panoramic views of the Nairobi city skyline and Karura Forest. Features double-height floor-to-ceiling glass, Italian designer kitchen, private rooftop terrace with jacuzzi, concierge services, and 4 dedicated basement parking slots.',
    purpose: 'rent',
    propertyType: 'penthouse',
    price: 4500,
    pricePeriod: 'month',
    currency: 'USD',
    country: 'Kenya',
    region: 'Nairobi County',
    city: 'Nairobi',
    area: 'Westlands',
    address: 'Githunguri Road, Westlands, Nairobi',
    coordinates: { lat: -1.2650, lng: 36.8090 },
    bedrooms: 4,
    bathrooms: 4,
    propertySizeSqft: 4800,
    yearBuilt: 2024,
    parkingSpaces: 4,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=85',
    features: ['Rooftop Jacuzzi', 'Miele Kitchen Appliances', 'Direct High-Speed Elevator Access', 'Heated Indoor Lap Pool', 'Fitness Club Membership Included', 'Full Power Backup'],
    amenities: ['Concierge 24/7', 'Gym', 'High Speed Fibre', 'Security', 'Terrace'],
    status: 'published',
    isFeatured: true,
    isVerified: true,
    viewsCount: 2950,
    favoritesCount: 140,
    inquiriesCount: 31,
    rating: 4.95,
    reviewsCount: 8,
    agentId: 'agent_nayyar',
    agencyId: 'agency_pamgolding',
    createdAt: '2025-08-01',
    updatedAt: '2025-08-25'
  },
  {
    id: 'prop_kigali_eco_villa',
    title: 'Kiyovu Hills Modern Eco-Villa',
    slug: 'kiyovu-hills-modern-eco-villa-kigali',
    description: 'Immaculately crafted 4-bedroom sustainable residence in Kigali’s premier diplomatic district. Designed with volcanic stone accents, rainwater harvesting, solar hybrid array, expansive entertainment deck, and tranquil garden overlooking Kigali green hills.',
    purpose: 'buy',
    propertyType: 'villa',
    price: 680000,
    pricePeriod: 'total',
    currency: 'USD',
    country: 'Rwanda',
    region: 'Kigali City',
    city: 'Kigali',
    area: 'Kiyovu',
    address: 'Avenue de la Justice, Kiyovu, Kigali',
    coordinates: { lat: -1.9540, lng: 30.0630 },
    bedrooms: 4,
    bathrooms: 4,
    propertySizeSqft: 4200,
    landSizeSqft: 12000,
    yearBuilt: 2023,
    parkingSpaces: 3,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=85',
    features: ['Solar Grid Hybrid 10kW', 'Landscaped Garden with Drip Irrigation', 'Ensuite Bedrooms with Walk-in Closets', 'Staff Quarters', 'Quiet Cul-de-sac'],
    amenities: ['Balcony', 'Garden', 'Solar Power', 'Security', 'Mountain View'],
    status: 'published',
    isFeatured: false,
    isVerified: true,
    viewsCount: 1890,
    favoritesCount: 94,
    inquiriesCount: 18,
    rating: 4.89,
    reviewsCount: 11,
    agentId: 'agent_david',
    agencyId: 'agency_century_rwanda',
    createdAt: '2025-08-05',
    updatedAt: '2025-08-20'
  },
  {
    id: 'prop_dar_peninsula',
    title: 'Masaki Ocean Bay Residence & Marina',
    slug: 'masaki-ocean-bay-residence-dar-es-salaam',
    description: 'Rare opportunity in Masaki peninsula, Dar es Salaam. Beautiful 4-bedroom townhome in an exclusive gated compound of 6 units with private boat mooring access, communal pool, and sweeping Indian Ocean breezes.',
    purpose: 'buy',
    propertyType: 'house',
    price: 590000,
    pricePeriod: 'total',
    currency: 'USD',
    country: 'Tanzania',
    region: 'Dar es Salaam',
    city: 'Dar es Salaam',
    area: 'Oysterbay & Masaki',
    address: 'Toure Drive, Masaki, Dar es Salaam',
    coordinates: { lat: -6.7550, lng: 39.2810 },
    bedrooms: 4,
    bathrooms: 4,
    propertySizeSqft: 3900,
    yearBuilt: 2022,
    parkingSpaces: 3,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
    features: ['Ocean Frontage', 'Gated Community with 24/7 Armed Response', 'Standby 100kVA Generator', 'Private Patio', 'Modern Hardwood Joinery'],
    amenities: ['Sea View', 'Communal Pool', 'Air Conditioning', 'Water Tanks', 'Security'],
    status: 'published',
    isFeatured: true,
    isVerified: true,
    viewsCount: 2200,
    favoritesCount: 115,
    inquiriesCount: 24,
    rating: 4.92,
    reviewsCount: 9,
    agentId: 'agent_amina',
    agencyId: 'agency_zanzibar_realty',
    createdAt: '2025-08-08',
    updatedAt: '2025-08-27'
  },
  {
    id: 'prop_kampala_kololo_apt',
    title: 'The Kololo Palms Executive 3-Bedroom Apartment',
    slug: 'kololo-palms-executive-apartment-kampala',
    description: 'Furnished upscale apartment in prime Kololo with expansive balcony overlooking the golf course. Fully serviced with housekeeping, swimming pool, gym, generator, and high-level diplomatic security.',
    purpose: 'rent',
    propertyType: 'apartment',
    price: 2600,
    pricePeriod: 'month',
    currency: 'USD',
    country: 'Uganda',
    region: 'Central Region',
    city: 'Kampala',
    area: 'Kololo Hill',
    address: 'Summit View Road, Kololo, Kampala',
    coordinates: { lat: 0.3290, lng: 32.5950 },
    bedrooms: 3,
    bathrooms: 3,
    propertySizeSqft: 2400,
    yearBuilt: 2023,
    parkingSpaces: 2,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=85',
    features: ['Fully Furnished with Designer Pieces', 'Golf Course Views', 'Rooftop Swimming Pool', 'Card Access & CCTV', 'Full Backup Power'],
    amenities: ['Furnished', 'Balcony', 'Gym', 'Swimming Pool', 'Fibre Internet'],
    status: 'published',
    isFeatured: false,
    isVerified: true,
    viewsCount: 1640,
    favoritesCount: 78,
    inquiriesCount: 19,
    rating: 4.88,
    reviewsCount: 7,
    agentId: 'agent_brian',
    createdAt: '2025-08-11',
    updatedAt: '2025-08-26'
  },
  {
    id: 'prop_naivasha_golf_residence',
    title: 'Great Rift Valley Lodge & Golf Resort Home',
    slug: 'great-rift-valley-lodge-golf-resort-home',
    description: 'Charming 4-bedroom holiday and lifestyle home perched above Lake Naivasha on an internationally renowned 18-hole championship golf estate. Panoramic views of Mount Longonot and the lake, with zebras and gazelles grazing on the fairways.',
    purpose: 'buy',
    propertyType: 'house',
    price: 490000,
    pricePeriod: 'total',
    currency: 'USD',
    country: 'Kenya',
    region: 'Nakuru County',
    city: 'Naivasha',
    area: 'Greenpark Estate',
    address: 'Great Rift Valley Lodge, Eburru Hill, Naivasha',
    coordinates: { lat: -0.6800, lng: 36.3500 },
    bedrooms: 4,
    bathrooms: 4,
    propertySizeSqft: 3600,
    landSizeSqft: 43560,
    landAcreage: 1.0,
    yearBuilt: 2021,
    parkingSpaces: 4,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=85',
    features: ['Championship Golf Membership', 'Private Airstrip Access', 'Lake Views', 'Hardwood Cedar Ceilings', 'Stone Fireplace', 'Solar Heating'],
    amenities: ['Golf Course', 'Tennis Court', 'Lake View', 'Clubhouse', 'Fireplace'],
    status: 'published',
    isFeatured: true,
    isVerified: true,
    viewsCount: 2410,
    favoritesCount: 130,
    inquiriesCount: 22,
    rating: 4.97,
    reviewsCount: 15,
    agentId: 'agent_faith',
    createdAt: '2025-08-02',
    updatedAt: '2025-08-22'
  },
  {
    id: 'prop_kilimani_smart_apt',
    title: 'The Lumina 2-Bedroom Urban Investment Suite',
    slug: 'lumina-2-bedroom-urban-investment-suite-kilimani',
    description: 'High-yielding modern apartment in Kilimani, Nairobi. Features biometric door locks, high speed lifts, heated rooftop pool, residents lounge and coffee shop. High demand for Airbnb and long-term corporate tenants.',
    purpose: 'buy',
    propertyType: 'apartment',
    price: 135000,
    pricePeriod: 'total',
    currency: 'USD',
    country: 'Kenya',
    region: 'Nairobi County',
    city: 'Nairobi',
    area: 'Kilimani',
    address: 'Dennis Pritt Road, Kilimani, Nairobi',
    coordinates: { lat: -1.2910, lng: 36.7860 },
    bedrooms: 2,
    bathrooms: 2,
    propertySizeSqft: 1100,
    yearBuilt: 2024,
    parkingSpaces: 1,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=85',
    features: ['High Rental Yield 12%', 'Rooftop Heated Pool', 'Fully Equipped Gym', 'High-Speed Lifts', 'Backup Generator & Borehole'],
    amenities: ['Gym', 'Swimming Pool', 'Elevator', 'Security 24/7', 'Balcony'],
    status: 'published',
    isFeatured: false,
    isVerified: true,
    viewsCount: 3820,
    favoritesCount: 205,
    inquiriesCount: 42,
    rating: 4.91,
    reviewsCount: 16,
    agentId: 'agent_nayyar',
    agencyId: 'agency_pamgolding',
    createdAt: '2025-08-16',
    updatedAt: '2025-08-29'
  }
];

export const INITIAL_LAND_LISTINGS: LandListing[] = [
  {
    id: 'land_nanyuki_ranches',
    title: '50-Acre Wildlife & Agribusiness Estate - Mount Kenya Views',
    slug: '50-acre-wildlife-agribusiness-estate-nanyuki',
    description: 'Exceptional 50-acre prime agricultural and lifestyle parcel directly facing Mount Kenya. Cleared perimeter, red volcanic soil, river frontage, and all-weather murram road access. Ideal for private luxury safari ranch, macadamia/avocado farming, or eco-lodge development.',
    purpose: 'sale',
    landType: 'agricultural',
    totalAcreage: 50,
    price: 750000,
    pricePerAcre: 15000,
    currency: 'USD',
    country: 'Kenya',
    region: 'Laikipia County',
    city: 'Nanyuki',
    area: 'Daiga & Ol Pejeta Corridor',
    titleDeedStatus: 'Ready Title Deed',
    tenure: 'Freehold',
    zoning: 'Agricultural',
    roadAccess: 'All-weather Murram',
    waterAccess: true,
    electricityAccess: true,
    fenced: true,
    developmentStatus: 'Cleared',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=85',
    status: 'published',
    isFeatured: true,
    isVerified: true,
    agentId: 'agent_faith',
    createdAt: '2025-08-04'
  },
  {
    id: 'land_zanzibar_beach_plot',
    title: '3.5-Acre Pristine Oceanfront Hotel & Resort Development Land',
    slug: '3-point-5-acre-oceanfront-resort-land-zanzibar',
    description: 'Prime oceanfront development plot in Paje, Zanzibar with 120 meters of pristine white sand beach frontage. ZIPA investment clearance eligible for 100% foreign ownership. Topography is level and ready for boutique 5-star eco-resort construction.',
    purpose: 'sale',
    landType: 'beach',
    totalAcreage: 3.5,
    price: 1800000,
    pricePerAcre: 514285,
    currency: 'USD',
    country: 'Tanzania',
    region: 'Zanzibar South',
    city: 'Zanzibar',
    area: 'Paje Beach',
    titleDeedStatus: 'Leasehold 99 Years',
    tenure: 'Leasehold',
    zoning: 'Commercial',
    roadAccess: 'Tarmac',
    waterAccess: true,
    electricityAccess: true,
    fenced: true,
    developmentStatus: 'Serviced Plots',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85',
    status: 'published',
    isFeatured: true,
    isVerified: true,
    agentId: 'agent_amina',
    createdAt: '2025-08-12'
  },
  {
    id: 'land_tatu_city_commercial',
    title: '1-Acre Commercial & Light Industrial Plot - Tatu City SEZ',
    slug: '1-acre-commercial-plot-tatu-city-sez-nairobi',
    description: 'Located in the prestigious Tatu City Special Economic Zone (SEZ) in Kiambu/Nairobi. Enjoy preferential corporate tax rates, zero VAT on construction materials, underground 3-phase power, treated water, paved roads, and 24/7 dedicated security.',
    purpose: 'sale',
    landType: 'commercial',
    totalAcreage: 1.0,
    price: 480000,
    pricePerAcre: 480000,
    currency: 'USD',
    country: 'Kenya',
    region: 'Kiambu / Nairobi',
    city: 'Nairobi',
    area: 'Tatu City SEZ',
    titleDeedStatus: 'Ready Title Deed',
    tenure: 'Leasehold',
    zoning: 'Commercial',
    roadAccess: 'Tarmac',
    waterAccess: true,
    electricityAccess: true,
    fenced: true,
    developmentStatus: 'Serviced Plots',
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=85',
    status: 'published',
    isFeatured: true,
    isVerified: true,
    agentId: 'agent_nayyar',
    createdAt: '2025-08-15'
  }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh_lc300_gr_sport',
    title: '2024 Toyota Land Cruiser LC300 GR-Sport 3.3L V6 Twin-Turbo Diesel',
    slug: '2024-toyota-land-cruiser-lc300-gr-sport',
    make: 'Toyota',
    model: 'Land Cruiser LC300 GR-Sport',
    year: 2024,
    price: 185000,
    currency: 'USD',
    bodyType: 'suv',
    condition: 'brand_new',
    mileageKm: 1200,
    fuelType: 'diesel',
    transmission: 'automatic',
    engineSizeCc: 3300,
    driveType: '4WD',
    color: 'Pearl White Crystal',
    location: 'Nairobi, Kenya',
    country: 'Kenya',
    vin: 'JTMAB33J8P5098124',
    importStatus: 'Duty Paid / Registered',
    sellerType: 'dealer',
    dealershipId: 'dealer_kilimanjaro',
    images: [
      'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=1200&auto=format&fit=crop&q=85',
    features: ['E-KDSS Suspension System', '360 Panoramic Multi-Terrain Monitor', 'JBL Premium 14-Speaker Sound', 'Heated & Ventilated Red/Black Leather', 'Sunroof', 'Head-Up Display', 'Rear Entertainment Screens'],
    description: 'The pinnacle of luxury expedition vehicles. Brand new 2024 Toyota Land Cruiser 300 series GR Sport in showroom condition. Full duty paid, KDK registration ready. 3 years/100,000km warranty backed by Kilimanjaro Motors.',
    status: 'published',
    isFeatured: true,
    isVerified: true,
    viewsCount: 5210,
    favoritesCount: 280,
    rating: 4.98,
    createdAt: '2025-08-18'
  },
  {
    id: 'veh_defender_110_v8',
    title: '2023 Land Rover Defender 110 V8 Carpathian Edition',
    slug: '2023-land-rover-defender-110-v8-carpathian',
    make: 'Land Rover',
    model: 'Defender 110 V8',
    year: 2023,
    price: 142000,
    currency: 'USD',
    bodyType: 'suv',
    condition: 'foreign_used',
    mileageKm: 18500,
    fuelType: 'petrol',
    transmission: 'automatic',
    engineSizeCc: 5000,
    driveType: 'AWD',
    color: 'Carpathian Grey Satin',
    location: 'Dar es Salaam, Tanzania',
    country: 'Tanzania',
    vin: 'SALUR2V83PA129841',
    importStatus: 'Duty Paid / Registered',
    sellerType: 'dealer',
    dealershipId: 'dealer_tanzania_prime',
    images: [
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=1200&auto=format&fit=crop&q=85',
    features: ['518 HP Supercharged V8', 'Electronic Air Suspension', '22-inch Gloss Black Alloys', 'Meridian Surround Sound', 'Alcantara Suede Steering Wheel', 'Tow Pack with Advanced Assist'],
    description: 'Flawless UK import with full service history. Incredible performance and unmatched prestige on city streets and African overland trails.',
    status: 'published',
    isFeatured: true,
    isVerified: true,
    viewsCount: 3890,
    favoritesCount: 195,
    rating: 4.95,
    createdAt: '2025-08-20'
  },
  {
    id: 'veh_mercedes_g63_amg',
    title: '2022 Mercedes-AMG G63 BiTurbo Night Package',
    slug: '2022-mercedes-amg-g63-biturbo-night-package',
    make: 'Mercedes-Benz',
    model: 'G-Class G63 AMG',
    year: 2022,
    price: 215000,
    currency: 'USD',
    bodyType: 'suv',
    condition: 'foreign_used',
    mileageKm: 24000,
    fuelType: 'petrol',
    transmission: 'automatic',
    engineSizeCc: 4000,
    driveType: 'AWD',
    color: 'Obsidian Black Metallic',
    location: 'Nairobi, Kenya',
    country: 'Kenya',
    vin: 'WDB4632761X892144',
    importStatus: 'Duty Paid / Registered',
    sellerType: 'dealer',
    dealershipId: 'dealer_kilimanjaro',
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=85',
    features: ['577 HP Handcrafted AMG V8', 'Burmester High-End 3D Audio', 'Nappa Leather Diamond Stitching', 'AMG Performance Exhaust', 'AMG Carbon Fiber Interior Trim'],
    description: 'Iconic luxury SUV in showroom condition. Serviced exclusively at DT Dobie Nairobi. Ceramic coated with 5-year paint protection.',
    status: 'published',
    isFeatured: true,
    isVerified: true,
    viewsCount: 4620,
    favoritesCount: 230,
    rating: 5.0,
    createdAt: '2025-08-21'
  },
  {
    id: 'veh_hilux_gr_sport',
    title: '2024 Toyota Hilux GR-Sport 2.8L 4x4 Double Cab',
    slug: '2024-toyota-hilux-gr-sport-double-cab',
    make: 'Toyota',
    model: 'Hilux GR Sport',
    year: 2024,
    price: 68000,
    currency: 'USD',
    bodyType: 'truck',
    condition: 'brand_new',
    mileageKm: 50,
    fuelType: 'diesel',
    transmission: 'automatic',
    engineSizeCc: 2800,
    driveType: '4WD',
    color: 'Attitude Black / Crimson Accents',
    location: 'Kigali, Rwanda',
    country: 'Rwanda',
    importStatus: 'Brand New Dealership',
    sellerType: 'dealer',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85',
    features: ['GR Monotube Shocks', 'Wide-Track Suspension', 'Leather/Suede GR Embossed Seats', 'Paddle Shifters', 'Tubliner & Roller Shutter'],
    description: 'The ultimate commercial and adventure utility pickup. Rugged reliability engineered with Gazoo Racing performance DNA.',
    status: 'published',
    isFeatured: false,
    isVerified: true,
    viewsCount: 2150,
    favoritesCount: 110,
    rating: 4.9,
    createdAt: '2025-08-23'
  }
];

export const INITIAL_EXPERIENCES: Experience[] = [
  {
    id: 'exp_masai_mara_balloon',
    title: 'Sunrise Hot Air Balloon Safari & Bush Champagne Breakfast',
    slug: 'sunrise-hot-air-balloon-safari-masai-mara',
    category: 'safari',
    country: 'Kenya',
    city: 'Masai Mara Game Reserve',
    location: 'Mara Triangle, Narok',
    pricePerPerson: 480,
    currency: 'USD',
    duration: '4.5 Hours',
    groupSize: 'Max 12 Guests',
    languages: ['English', 'Swahili', 'French'],
    included: ['1-Hour Balloon Flight at Dawn', 'Bush Champagne English Breakfast', 'Game Drive Transfer', 'Flight Certificate signed by Captain'],
    images: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=85',
    description: 'Float gracefully above the vast golden plains of the Masai Mara at dawn as the Great Migration thunders below. Spot prides of lions, herds of elephants, and giraffes from a breathtaking vantage point before descending to a white-linen bush breakfast.',
    rating: 4.99,
    reviewsCount: 142,
    hostName: 'Captain Patrick Njoroge',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'published',
    isFeatured: true
  },
  {
    id: 'exp_zanzibar_dhow_safari_blue',
    title: 'Safari Blue Traditional Dhow & Sandbank Snorkeling Feast',
    slug: 'safari-blue-dhow-sandbank-zanzibar',
    category: 'sailing',
    country: 'Tanzania',
    city: 'Zanzibar',
    location: 'Menai Bay Conservation Area, Fumba',
    pricePerPerson: 95,
    currency: 'USD',
    duration: '7 Hours',
    groupSize: 'Small Groups',
    languages: ['English', 'Swahili', 'Italian'],
    included: ['Handcrafted Dhow Sailing', 'Pristine Sandbank Stop', 'Grilled Seafood Lobster Feast', 'Snorkeling Equipment & Marine Guide'],
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=85',
    description: 'Sail in handcrafted wooden dhows across the Menai Bay marine reserve, swim with tropical dolphins, snorkel through untouched coral gardens, and indulge in a banquet of slipper lobster and Swahili spiced delicacies on Kwale Island.',
    rating: 4.96,
    reviewsCount: 210,
    hostName: 'Captain Salum & Crew',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'published',
    isFeatured: true
  },
  {
    id: 'exp_gorilla_trek_rwanda',
    title: 'Volcanoes National Park Mountain Gorilla Tracking Masterclass',
    slug: 'volcanoes-national-park-mountain-gorilla-tracking-rwanda',
    category: 'wildlife',
    country: 'Rwanda',
    city: 'Musanze',
    location: 'Kinigi Headquarters, Volcanoes National Park',
    pricePerPerson: 1500,
    currency: 'USD',
    duration: 'Full Day',
    groupSize: '8 Guests per Gorilla Family',
    languages: ['English', 'French', 'Kinyarwanda'],
    included: ['Official RDB Gorilla Permit Assist', 'Expert Primatologist Guide', 'Porters & Walking Sticks', 'Post-Trek Cultural Celebration'],
    images: [
      'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=1200&auto=format&fit=crop&q=85',
    description: 'An unforgettable encounter with the majestic endangered mountain gorillas in the misty bamboo forests of the Virunga volcanoes.',
    rating: 5.0,
    reviewsCount: 98,
    hostName: 'Jean-Paul Habimana',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'published',
    isFeatured: true
  }
];

export const INITIAL_STAYS: Stay[] = [
  {
    id: 'stay_lamu_shela_house',
    title: 'The Coral Swahili Palace in Shela Beach',
    slug: 'coral-swahili-palace-shela-beach-lamu',
    stayType: 'villa',
    country: 'Kenya',
    city: 'Lamu Island',
    area: 'Shela Village',
    pricePerNight: 380,
    currency: 'USD',
    guests: 8,
    bedrooms: 4,
    bathrooms: 4,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&auto=format&fit=crop&q=85',
    amenities: ['Private Chef Included', 'Rooftop Lounge', 'Plunge Pool', 'Dhow Transfers', 'WiFi'],
    rating: 4.98,
    reviewsCount: 64,
    isGuestFavorite: true,
    isVerified: true,
    hostName: 'Fatma & Ali',
    hostAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'stay_serengeti_luxury_camp',
    title: 'Acacia Safari Glamping Haven - Serengeti',
    slug: 'acacia-safari-glamping-haven-serengeti',
    stayType: 'safari_camp',
    country: 'Tanzania',
    city: 'Serengeti National Park',
    area: 'Central Seronera',
    pricePerNight: 650,
    currency: 'USD',
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=85'
    ],
    featuredImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=85',
    amenities: ['All Meals & Wine Included', 'Private Game Drives', 'Campfire Astronomy', 'Ensuite Copper Baths'],
    rating: 5.0,
    reviewsCount: 52,
    isGuestFavorite: true,
    isVerified: true,
    hostName: 'Serengeti Wilderness Collection',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  }
];

export const INITIAL_LEADS: CRMLead[] = [
  {
    id: 'lead_1',
    name: 'Marcus Vance',
    email: 'marcus.vance@investcapital.co.uk',
    phone: '+44 7700 900123',
    source: 'Website Inquiry',
    interestedItemType: 'property',
    interestedItemId: 'prop_karen_villa',
    interestedItemTitle: 'The Orchid Grand Estate - Karen',
    budget: 1500000,
    currency: 'USD',
    location: 'London / Relocating to Nairobi',
    status: 'viewing',
    agentId: 'agent_nayyar',
    assignedAgentName: 'Nayyar Shaikh',
    score: 95,
    notes: 'British tech entrepreneur relocating family to Nairobi in November. Prefers secure acre compound near Hillcrest or Brookhouse schools.',
    lastActivity: 'Scheduled viewing for Saturday 11:00 AM',
    nextFollowUp: '2026-09-04',
    dealValue: 1450000,
    createdAt: '2025-08-25'
  },
  {
    id: 'lead_2',
    name: 'Zuhura Al-Mansoor',
    email: 'zuhura.mansoor@gulfholding.ae',
    phone: '+971 50 443 8899',
    source: 'WhatsApp Direct',
    interestedItemType: 'land',
    interestedItemId: 'land_zanzibar_beach_plot',
    interestedItemTitle: '3.5-Acre Pristine Oceanfront Paje Land',
    budget: 2000000,
    currency: 'USD',
    location: 'Dubai, UAE',
    status: 'negotiation',
    agentId: 'agent_amina',
    assignedAgentName: 'Amina Kimaro',
    score: 88,
    notes: 'Hospitality developer looking to build luxury 20-key wellness resort in Zanzibar. Requested ZIPA legal guidelines and draft sale agreement.',
    lastActivity: 'Sent land survey documents & title search cert',
    nextFollowUp: '2026-09-03',
    dealValue: 1800000,
    createdAt: '2025-08-22'
  },
  {
    id: 'lead_3',
    name: 'Dr. Kevin Mutua',
    email: 'k.mutua@nairobihospital.org',
    phone: '+254 722 888 111',
    source: 'Ad Campaign',
    interestedItemType: 'vehicle',
    interestedItemId: 'veh_lc300_gr_sport',
    interestedItemTitle: '2024 Toyota Land Cruiser LC300 GR-Sport',
    budget: 190000,
    currency: 'USD',
    location: 'Nairobi, Kenya',
    status: 'qualified',
    agentId: 'agent_nayyar',
    assignedAgentName: 'Nayyar Shaikh',
    score: 82,
    notes: 'Senior neurosurgeon looking for personal import upgrade. Interested in trade-in of 2019 Prado TX-L.',
    lastActivity: 'Sent trade-in evaluation estimate ($38,000)',
    nextFollowUp: '2026-09-05',
    dealValue: 185000,
    createdAt: '2025-08-28'
  },
  {
    id: 'lead_4',
    name: 'Elena Rostova',
    email: 'elena@nordicvoyages.se',
    phone: '+46 8 123 4567',
    source: 'Website Inquiry',
    interestedItemType: 'property',
    interestedItemId: 'prop_westlands_penthouse',
    interestedItemTitle: 'Skyline Pinnacle Duplex Penthouse',
    budget: 5000,
    currency: 'USD',
    location: 'Stockholm, Sweden',
    status: 'contacted',
    agentId: 'agent_nayyar',
    assignedAgentName: 'Nayyar Shaikh',
    score: 70,
    notes: 'UN consultant starting 2-year post in Gigiri in October. Needs fully serviced luxury flat with generator and gym.',
    lastActivity: 'Sent video walkthrough via WhatsApp',
    nextFollowUp: '2026-09-06',
    dealValue: 54000,
    createdAt: '2025-08-29'
  }
];

export const INITIAL_BOOKINGS: BookingReservation[] = [
  {
    id: 'bk_37495',
    userId: 'usr_nayyar',
    userName: 'Marcus Vance',
    userEmail: 'marcus.vance@investcapital.co.uk',
    userPhone: '+44 7700 900123',
    type: 'property_viewing',
    itemId: 'prop_karen_villa',
    itemTitle: 'The Orchid Grand Estate - 5 Bedroom Luxury Villa',
    itemType: 'Property',
    date: '2026-09-06',
    time: '11:00 AM',
    status: 'upcoming',
    notes: 'Client arriving with spouse and family architect.',
    createdAt: '2026-09-01'
  },
  {
    id: 'bk_37487',
    userId: 'usr_nayyar',
    userName: 'Dr. Kevin Mutua',
    userEmail: 'k.mutua@nairobihospital.org',
    userPhone: '+254 722 888 111',
    type: 'vehicle_test_drive',
    itemId: 'veh_lc300_gr_sport',
    itemTitle: '2024 Toyota Land Cruiser LC300 GR-Sport',
    itemType: 'Vehicle',
    date: '2026-09-07',
    time: '02:30 PM',
    status: 'upcoming',
    notes: 'Mombasa Road dealership showroom test drive on Southern Bypass.',
    createdAt: '2026-09-01'
  },
  {
    id: 'bk_37470',
    userId: 'usr_nayyar',
    userName: 'Sarah Jenkins',
    userEmail: 'sarah.j@gmail.com',
    userPhone: '+1 415 889 2200',
    type: 'stay_reservation',
    itemId: 'stay_lamu_shela_house',
    itemTitle: 'The Coral Swahili Palace in Shela Beach',
    itemType: 'Stay',
    date: '2026-09-20 to 2026-09-26',
    time: 'Check-in 2:00 PM',
    status: 'upcoming',
    guestsCount: 4,
    totalPrice: 2280,
    currency: 'USD',
    notes: 'Requested private Swahili seafood dinner on arrival.',
    createdAt: '2026-09-01'
  }
];

export const INITIAL_AD_CAMPAIGNS: AdCampaign[] = [
  {
    id: 'ad_camp_101',
    userId: 'usr_nayyar',
    advertiserName: 'Pam Golding Properties East Africa',
    title: 'Karen Luxury Estates - Diaspora Investor Push',
    objective: 'leads',
    targetCategory: 'property',
    promotedItemId: 'prop_karen_villa',
    promotedItemTitle: 'The Orchid Grand Estate - Karen',
    headline: 'Secure Prime 1.25-Acre Gated Living in Karen, Nairobi',
    description: 'Modern luxury finishes, private heated pool, borehole & solar backup. Freehold title ready.',
    callToAction: 'Book Viewing',
    destinationUrl: '/properties/orchid-grand-estate-karen-nairobi',
    creativeImageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=85',
    targetLocations: ['Kenya', 'United Kingdom', 'United States', 'UAE', 'Tanzania'],
    targetAudienceInterests: ['Real Estate Investing', 'Luxury Homes', 'East Africa Diaspora', 'Golf Estates'],
    placements: ['homepage_hero', 'search_top', 'sponsored_card'],
    budgetType: 'daily',
    budgetAmount: 85,
    spentAmount: 510,
    currency: 'USD',
    startDate: '2025-08-20',
    endDate: '2025-09-30',
    status: 'active',
    impressions: 48920,
    clicks: 2180,
    leads: 64,
    conversions: 18,
    ctr: 4.45,
    costPerLead: 7.96,
    riskScore: 'low',
    createdAt: '2025-08-19'
  },
  {
    id: 'ad_camp_102',
    userId: 'usr_dealer_hassan',
    advertiserName: 'Kilimanjaro Motors',
    title: 'Brand New LC300 GR-Sport Showroom Showcase',
    objective: 'promote_listing',
    targetCategory: 'vehicle',
    promotedItemId: 'veh_lc300_gr_sport',
    promotedItemTitle: '2024 Toyota Land Cruiser LC300 GR-Sport',
    headline: 'Drive the 2024 LC300 GR-Sport Today in Nairobi & Dar',
    description: 'Full duty paid, 3-year warranty, attractive asset financing available with Stanbic & KCB.',
    callToAction: 'Get Best Deal',
    destinationUrl: '/vehicles/2024-toyota-land-cruiser-lc300-gr-sport',
    creativeImageUrl: 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=1000&auto=format&fit=crop&q=85',
    targetLocations: ['Kenya', 'Tanzania', 'Uganda', 'Rwanda'],
    targetAudienceInterests: ['Toyota Land Cruiser', '4x4 Off-Road', 'Executive Vehicles'],
    placements: ['vehicle_feed', 'search_top', 'sponsored_card'],
    budgetType: 'lifetime',
    budgetAmount: 1200,
    spentAmount: 840,
    currency: 'USD',
    startDate: '2025-08-15',
    endDate: '2025-09-15',
    status: 'active',
    impressions: 34100,
    clicks: 1640,
    leads: 41,
    conversions: 9,
    ctr: 4.80,
    costPerLead: 20.48,
    riskScore: 'low',
    createdAt: '2025-08-14'
  },
  {
    id: 'ad_camp_103',
    userId: 'usr_nayyar',
    advertiserName: 'Zanzibar Coral Coast Properties',
    title: 'Paje Oceanfront Plots - High Yield Hospitality',
    objective: 'leads',
    targetCategory: 'land',
    promotedItemId: 'land_zanzibar_beach_plot',
    promotedItemTitle: '3.5-Acre Oceanfront Paje Land',
    headline: 'Invest in Zanzibar White Sands: 100% Foreign Ownership Eligible',
    description: '120m direct beach frontage, ready for boutique hotel development.',
    callToAction: 'Contact Agent',
    destinationUrl: '/land',
    creativeImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=85',
    targetLocations: ['UAE', 'Saudi Arabia', 'United Kingdom', 'Germany', 'Italy'],
    targetAudienceInterests: ['Hotel Investment', 'Zanzibar Tourism', 'Beach Resorts'],
    placements: ['homepage_hero', 'sponsored_card'],
    budgetType: 'daily',
    budgetAmount: 120,
    spentAmount: 0,
    currency: 'USD',
    startDate: '2025-09-01',
    endDate: '2025-10-01',
    status: 'pending_review',
    impressions: 0,
    clicks: 0,
    leads: 0,
    conversions: 0,
    ctr: 0,
    costPerLead: 0,
    riskScore: 'low',
    createdAt: '2025-08-31'
  }
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv_37480',
    invoiceNumber: 'INV-2025-37480',
    userId: 'usr_nayyar',
    userName: 'Nayyar Shaikh',
    userEmail: 'nayyar.shaikh@safarinest.africa',
    amount: 299,
    currency: 'USD',
    description: 'SafariNest Agency Tier Membership (Monthly Subscription)',
    paymentMethod: 'M-Pesa Express',
    status: 'paid',
    itemType: 'membership',
    date: '2025-08-20',
    dueDate: '2025-08-20'
  },
  {
    id: 'inv_37470',
    invoiceNumber: 'INV-2025-37470',
    userId: 'usr_nayyar',
    userName: 'Nayyar Shaikh',
    userEmail: 'nayyar.shaikh@safarinest.africa',
    amount: 510,
    currency: 'USD',
    description: 'Advertising Campaign Boost Budget - Karen Luxury Estates',
    paymentMethod: 'Credit Card / Stripe',
    status: 'paid',
    itemType: 'advertising_credits',
    date: '2025-08-19',
    dueDate: '2025-08-19'
  },
  {
    id: 'inv_37449',
    invoiceNumber: 'INV-2025-37449',
    userId: 'usr_dealer_hassan',
    userName: 'Hassan Mwinyi',
    userEmail: 'hassan@mwinyiauto.co.tz',
    amount: 840,
    currency: 'USD',
    description: 'Ad Credits Pre-Funding - Toyota LC300 Showcase',
    paymentMethod: 'Bank Transfer',
    status: 'paid',
    itemType: 'advertising_credits',
    date: '2025-08-14',
    dueDate: '2025-08-14'
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    targetId: 'agent_nayyar',
    targetType: 'agent',
    authorName: 'Ambassador Richard Mwangi',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Outstanding professionalism & discrete advisory',
    comment: 'Nayyar guided us seamlessly through purchasing our family residence in Karen. His market insights, legal diligence, and negotiation skills are unmatched in East Africa.',
    date: '2025-07-28',
    isVerifiedPurchase: true,
    status: 'approved'
  },
  {
    id: 'rev_2',
    targetId: 'agent_amina',
    targetType: 'agent',
    authorName: 'Giulia & Marco Rossi',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Made our Zanzibar dream villa a reality',
    comment: 'Amina handled all ZIPA paperwork, title registration, and local government approvals flawlessly. Our beachfront villa in Nungwi is already delivering fantastic rental income.',
    date: '2025-08-04',
    isVerifiedPurchase: true,
    status: 'approved'
  }
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    participantId: 'lead_1',
    participantName: 'Marcus Vance',
    participantAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    participantRole: 'Buyer / Investor',
    lastMessage: 'Looking forward to the Saturday viewing in Karen. Can you have the title deed deed plan copy on hand?',
    lastMessageTime: '10:45 AM',
    unreadCount: 1,
    itemContext: {
      type: 'property',
      id: 'prop_karen_villa',
      title: 'The Orchid Grand Estate - Karen',
      price: 1450000,
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&auto=format&fit=crop&q=80'
    }
  },
  {
    id: 'conv_2',
    participantId: 'lead_3',
    participantName: 'Dr. Kevin Mutua',
    participantAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    participantRole: 'Vehicle Buyer',
    lastMessage: 'Can we confirm the trade-in inspection at your showroom on Monday at 2 PM?',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    itemContext: {
      type: 'vehicle',
      id: 'veh_lc300_gr_sport',
      title: '2024 Toyota Land Cruiser LC300',
      price: 185000,
      image: 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=300&auto=format&fit=crop&q=80'
    }
  }
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  conv_1: [
    {
      id: 'msg_1',
      conversationId: 'conv_1',
      senderId: 'lead_1',
      senderName: 'Marcus Vance',
      senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
      text: 'Hi Nayyar, I saw your listing for The Orchid Grand Estate in Karen on SafariNest. It looks exceptional.',
      timestamp: 'Yesterday 3:15 PM',
      isRead: true
    },
    {
      id: 'msg_2',
      conversationId: 'conv_1',
      senderId: 'usr_nayyar',
      senderName: 'Nayyar Shaikh',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
      text: 'Good afternoon Marcus! Thank you for reaching out. Yes, it is one of the finest 1.25-acre properties currently available in Miotoni Karen.',
      timestamp: 'Yesterday 3:30 PM',
      isRead: true
    },
    {
      id: 'msg_3',
      conversationId: 'conv_1',
      senderId: 'lead_1',
      senderName: 'Marcus Vance',
      senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
      text: 'Looking forward to the Saturday viewing in Karen. Can you have the title deed deed plan copy on hand?',
      timestamp: '10:45 AM',
      isRead: false
    }
  ]
};

export const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post_1',
    title: 'Top 7 High-Growth Real Estate Suburbs in Nairobi for 2026',
    slug: 'top-7-high-growth-real-estate-suburbs-nairobi-2026',
    excerpt: 'An in-depth analysis of Westlands, Karen, Kilimani, and satellite growth corridors along the Nairobi Expressway.',
    content: 'East Africa’s economic capital continues to attract multinational headquarters and diaspora capital. Infrastructure developments such as the Nairobi Expressway, smart utility corridors in Tatu City, and diplomatic security standards have positioned specific neighborhoods for double-digit rental yields and long-term capital appreciation.',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1000&auto=format&fit=crop&q=85',
    category: 'Market Insights',
    authorName: 'Nayyar Shaikh',
    authorRole: 'Senior Luxury Advisor',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    publishedAt: 'August 24, 2025',
    readTime: '6 min read',
    tags: ['Nairobi', 'Investment', 'Real Estate', 'Diaspora'],
    featured: true
  },
  {
    id: 'post_2',
    title: 'A Foreign Investor’s Comprehensive Guide to Buying Land in Zanzibar',
    slug: 'foreign-investor-guide-buying-land-zanzibar-zipa',
    excerpt: 'Navigating ZIPA foreign ownership regulations, 99-year leaseholds, and high-return hospitality developments.',
    content: 'Zanzibar has emerged as the Indian Ocean’s most lucrative beachfront destination. With recent pro-investment legislation enacted by the Revolutionary Government of Zanzibar through ZIPA, non-citizens can securely acquire oceanfront villas and hotel land with zero currency restrictions and substantial tax holidays.',
    coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1000&auto=format&fit=crop&q=85',
    category: 'Legal & Advisory',
    authorName: 'Amina Kimaro',
    authorRole: 'Zanzibar Legal & Property Consultant',
    authorAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&auto=format&fit=crop&q=80',
    publishedAt: 'August 18, 2025',
    readTime: '8 min read',
    tags: ['Zanzibar', 'ZIPA', 'Beachfront', 'Hospitality'],
    featured: true
  },
  {
    id: 'post_3',
    title: 'Why Kigali is Becoming Africa’s Premier Green Architecture Capital',
    slug: 'why-kigali-green-architecture-capital-africa',
    excerpt: 'How Rwanda’s master plan, clean energy mandates, and modern eco-villas are setting a continental benchmark.',
    content: 'From spotless boulevards to progressive building codes requiring rainwater recycling and solar integration, Kigali is rapidly defining the future of African urbanism.',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1000&auto=format&fit=crop&q=85',
    category: 'Architecture & Design',
    authorName: 'David Mugisha',
    authorRole: 'Great Lakes Real Estate Director',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    publishedAt: 'August 12, 2025',
    readTime: '5 min read',
    tags: ['Kigali', 'Eco-Living', 'Green Architecture'],
    featured: false
  }
];

export const INITIAL_CUSTOM_FIELDS: CustomFieldDefinition[] = [
  { id: 'cf_1', category: 'property', name: 'title_deed_status', label: 'Title Deed Status', type: 'dropdown', options: ['Ready Title Deed', 'Freehold', 'Sectional Title', 'Processing', 'Allotment Letter'], required: true, filterable: true, searchable: true, order: 1 },
  { id: 'cf_2', category: 'property', name: 'water_supply', label: 'Water Infrastructure', type: 'dropdown', options: ['Borehole On-site', 'City Council Connected', 'Desalination Plant', 'Rainwater Harvesting', 'Tank Storage'], required: false, filterable: true, searchable: true, order: 2 },
  { id: 'cf_3', category: 'property', name: 'power_backup', label: 'Power Backup & Solar', type: 'dropdown', options: ['Full Generator Backup', 'Solar Hybrid Array', 'Inverter System', 'Grid Only'], required: false, filterable: true, searchable: true, order: 3 },
  { id: 'cf_4', category: 'land', name: 'tenure_type', label: 'Land Tenure', type: 'dropdown', options: ['Freehold', 'Leasehold 99 Years', 'Leasehold 50 Years', 'Customary'], required: true, filterable: true, searchable: true, order: 1 },
  { id: 'cf_5', category: 'land', name: 'road_frontage', label: 'Road Frontage Type', type: 'dropdown', options: ['Tarmac Highway', 'Paved Feeder Road', 'All-weather Murram', 'Graded Earth'], required: true, filterable: true, searchable: true, order: 2 },
  { id: 'cf_6', category: 'vehicle', name: 'import_duty_status', label: 'Import Duty & Registration', type: 'dropdown', options: ['Duty Fully Paid & Numbered', 'Direct Import In-Transit', 'Ex-Diplomatic Duty Free', 'Showroom Bonded'], required: true, filterable: true, searchable: true, order: 1 }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    userId: 'usr_nayyar',
    title: 'New High-Value Lead Assigned',
    message: 'Marcus Vance inquired about The Orchid Grand Estate in Karen ($1.45M).',
    type: 'inquiry',
    link: '/dashboard/crm',
    isRead: false,
    createdAt: '15 mins ago'
  },
  {
    id: 'notif_2',
    userId: 'usr_nayyar',
    title: 'Viewing Request Scheduled',
    message: 'Property viewing confirmed for Orchid Grand Estate on Saturday 11:00 AM.',
    type: 'booking',
    link: '/dashboard/bookings',
    isRead: false,
    createdAt: '1 hour ago'
  },
  {
    id: 'notif_3',
    userId: 'usr_nayyar',
    title: 'Ad Campaign Approved & Active',
    message: 'Your campaign "Karen Luxury Estates - Diaspora Push" is now running live.',
    type: 'ad_approved',
    link: '/dashboard/advertising',
    isRead: true,
    createdAt: 'Yesterday'
  }
];

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act_1',
    userId: 'usr_nayyar',
    action: 'Added Booking Request 37495',
    timestamp: 'September 24, 2024, 12:10 am',
    type: 'booking'
  },
  {
    id: 'act_2',
    userId: 'usr_nayyar',
    action: 'Added Booking Request 37487',
    timestamp: 'September 24, 2024, 12:08 am',
    type: 'booking'
  },
  {
    id: 'act_3',
    userId: 'usr_nayyar',
    action: 'Edited Booking Request 37479',
    timestamp: 'September 24, 2024, 12:05 am',
    type: 'booking'
  },
  {
    id: 'act_4',
    userId: 'usr_nayyar',
    action: 'Generated Invoice Invoice 37480',
    timestamp: 'September 24, 2024, 12:03 am',
    type: 'invoice'
  },
  {
    id: 'act_5',
    userId: 'usr_nayyar',
    action: 'Edited property Modern Boutique House',
    timestamp: 'September 24, 2024, 12:01 am',
    type: 'property'
  },
  {
    id: 'act_6',
    userId: 'usr_nayyar',
    action: 'Edited Booking Request 37471',
    timestamp: 'September 24, 2024, 11:58 pm',
    type: 'booking'
  },
  {
    id: 'act_7',
    userId: 'usr_nayyar',
    action: 'Generated Invoice Invoice 37470',
    timestamp: 'September 24, 2024, 11:55 pm',
    type: 'invoice'
  },
  {
    id: 'act_8',
    userId: 'usr_nayyar',
    action: "Edited property Aloha Kona's Bungalow",
    timestamp: 'September 24, 2024, 11:50 pm',
    type: 'property'
  },
  {
    id: 'act_9',
    userId: 'usr_nayyar',
    action: 'Generated Invoice Invoice 37449',
    timestamp: 'September 24, 2024, 11:45 pm',
    type: 'invoice'
  },
  {
    id: 'act_10',
    userId: 'usr_nayyar',
    action: 'Added Booking Request 37446',
    timestamp: 'September 24, 2024, 11:40 pm',
    type: 'booking'
  }
];
